# This is a basic workflow to help you get started with Actions

name: Windows CLI Build

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          haxelib setup C:/haxelib
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install haxeui-flixel
          haxelib git flixel-leather https://github.com/Leather128/flixel
          haxelib git console https://github.com/haxiomic/console.hx
          haxelib install flixel-ui
          haxelib git openfl https://github.com/openfl/openfl
          haxelib git hscript-improved https://github.com/YoshiCrafter29/hscript-improved
          haxelib install lime
          haxelib run lime setup
          haxelib run lime build windows
          
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: export/release/windows/bin